In [1]:
import torch
import numpy

def get_pad_mask(seq, pad_idx):
    return (seq != pad_idx).unsqueeze(-2)

def get_subsequent_mask(seq):
    """For masking out the subsequent info."""
    sz_b, len_s = seq.size()
    subsequent_mask = (1 - torch.triu(
        torch.ones((1, len_s, len_s), device=seq.device), diagonal=1)).bool()
    
    return subsequent_mask

X = torch.tensor([[1, 2, 3], [0, 3, 4], [1, 0, 3]])
print(X)
print(X.shape)
Y = get_pad_mask(X, 0)
print(Y)
print(Y.shape)
Z = get_subsequent_mask(X)
print(Z)
print(Z.shape)

tensor([[1, 2, 3],
        [0, 3, 4],
        [1, 0, 3]])
torch.Size([3, 3])
tensor([[[ True,  True,  True]],

        [[False,  True,  True]],

        [[ True, False,  True]]])
torch.Size([3, 1, 3])
tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])
torch.Size([1, 3, 3])


In [2]:
X = torch.rand((16, 256, 128))
print("X.shape: ", X.shape)
# X = X.transpose(0, 1)
X_steps = X.chunk(256, 1)
X_steps = [sample.squeeze(1) for sample in X_steps]
print("X_steps size:", len(X_steps))
print("X_steps[0].shape: ", X_steps[0].shape)
print("X_steps[0]: ", X_steps[0])

X.shape:  torch.Size([16, 256, 128])
X_steps size: 256
X_steps[0].shape:  torch.Size([16, 128])
X_steps[0]:  tensor([[0.2819, 0.0169, 0.9211,  ..., 0.6987, 0.1143, 0.4208],
        [0.3745, 0.3468, 0.9360,  ..., 0.6076, 0.2222, 0.8276],
        [0.2868, 0.0114, 0.7942,  ..., 0.2099, 0.5915, 0.7888],
        ...,
        [0.9203, 0.1610, 0.0179,  ..., 0.3154, 0.8679, 0.6536],
        [0.0091, 0.2517, 0.0125,  ..., 0.4794, 0.4094, 0.9625],
        [0.5499, 0.8150, 0.7648,  ..., 0.2280, 0.6088, 0.5262]])


In [4]:
from BagOfWords import *
sentences = [
    'Game of Thrones is an amazing tv series!',
    'Game of Thrones is the best tv series!',
    'Game of Thrones is so great']
bow = BagOfWord(sentences)
print("preprocessing data:")
input = 'Game of Thrones is an great tv series! an an an abc'
output = bow(input)
print(output)

preprocessing data:
tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0., 10.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  5.],
        [ 0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.],
        [ 0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  4.],
        [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0., 11.],
        [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  7.],
        [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
        [ 0.,  2.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
        [ 0.,  3.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
        [ 0.,  4.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1., 12.]],
       dtype=torch.float64)
