In [1]:
import torch
import numpy

def get_pad_mask(seq, pad_idx):
    return (seq != pad_idx).unsqueeze(-2)

def get_subsequent_mask(seq):
    """For masking out the subsequent info."""
    sz_b, len_s = seq.size()
    subsequent_mask = (1 - torch.triu(
        torch.ones((1, len_s, len_s), device=seq.device), diagonal=1)).bool()
    
    return subsequent_mask

X = torch.tensor([[1, 2, 3], [0, 3, 4], [1, 0, 3]])
print(X)
print(X.shape)
Y = get_pad_mask(X, 0)
print(Y)
print(Y.shape)
Z = get_subsequent_mask(X)
print(Z)
print(Z.shape)

tensor([[1, 2, 3],
        [0, 3, 4],
        [1, 0, 3]])
torch.Size([3, 3])
tensor([[[ True,  True,  True]],

        [[False,  True,  True]],

        [[ True, False,  True]]])
torch.Size([3, 1, 3])
tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])
torch.Size([1, 3, 3])


In [2]:
X = torch.rand((16, 256, 128))
print("X.shape: ", X.shape)
# X = X.transpose(0, 1)
X_steps = X.chunk(256, 1)
X_steps = [sample.squeeze(1) for sample in X_steps]
print("X_steps size:", len(X_steps))
print("X_steps[0].shape: ", X_steps[0].shape)
print("X_steps[0]: ", X_steps[0])

X.shape:  torch.Size([16, 256, 128])
X_steps size: 256
X_steps[0].shape:  torch.Size([16, 128])
X_steps[0]:  tensor([[0.1162, 0.8061, 0.8392,  ..., 0.1928, 0.5298, 0.9624],
        [0.9531, 0.3707, 0.3462,  ..., 0.8726, 0.8356, 0.2774],
        [0.3794, 0.8660, 0.6447,  ..., 0.3528, 0.7741, 0.8680],
        ...,
        [0.6861, 0.2432, 0.6732,  ..., 0.5059, 0.7247, 0.0567],
        [0.6160, 0.7700, 0.2920,  ..., 0.9479, 0.4963, 0.5042],
        [0.6372, 0.1501, 0.6515,  ..., 0.0273, 0.0735, 0.4761]])


In [3]:
from BagOfWords import *
sentences = [
    'Game of Thrones is an amazing tv series!',
    'Game of Thrones is the best tv series!',
    'Game of Thrones is so great']
bow = BagOfWord(sentences)
print("preprocessing data:")
input = 'Game of Thrones is an great tv series! an an an abc'
output = bow(input)
i_vectors, s_vectors = output
print("i_vectors:")
print(i_vectors)
print("s_vectors:")
print(s_vectors)

preprocessing data:
i_vectors:
[tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]]), tensor([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]), tensor([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]), tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])]
s_vectors:
[tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.]]), tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]

In [6]:
v_vector = torch.cat((i_vectors[0], s_vectors[0]), dim=1)
print(v_vector)
print(v_vector.shape)

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.]])
torch.Size([1, 24])


In [26]:
x = torch.tensor([[1, 1, 1]])
y = torch.tensor([[2, 2, 2]])
z = torch.tensor([[3, 3, 3]])
print(x.shape)
t = torch.stack((x.squeeze(), y.squeeze(), z.squeeze()))
print(t.shape)
print(t)

torch.Size([1, 3])
torch.Size([3, 3])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
