In [6]:
import torch
import numpy

def get_pad_mask(seq, pad_idx):
    return (seq != pad_idx).unsqueeze(-2)

def get_subsequent_mask(seq):
    """For masking out the subsequent info."""
    sz_b, len_s = seq.size()
    subsequent_mask = (1 - torch.triu(
        torch.ones((1, len_s, len_s), device=seq.device), diagonal=1)).bool()
    
    return subsequent_mask

X = torch.tensor([[1, 2, 3], [0, 3, 4], [1, 0, 3]])
print(X)
print(X.shape)
Y = get_pad_mask(X, 0)
print(Y)
print(Y.shape)
Z = get_subsequent_mask(X)
print(Z)
print(Z.shape)

tensor([[1, 2, 3],
        [0, 3, 4],
        [1, 0, 3]])
torch.Size([3, 3])
tensor([[[ True,  True,  True]],

        [[False,  True,  True]],

        [[ True, False,  True]]])
torch.Size([3, 1, 3])
tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])
torch.Size([1, 3, 3])
